// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg32UUAsEdUkPN1o44UGGnBhoCNRdk0UI',
    appId: '1:355747839461:web:a24fa4041fb230d959430c',
    messagingSenderId: '355747839461',
    projectId: 'cpmad-assignment',
    authDomain: 'cpmad-assignment.firebaseapp.com',
    storageBucket: 'cpmad-assignment.appspot.com',
    measurementId: 'G-N41TE426D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChW2duNdkaoHBfZUVAXjN4kZ6E-YEZiWY',
    appId: '1:355747839461:android:680bb0f3f8031a8259430c',
    messagingSenderId: '355747839461',
    projectId: 'cpmad-assignment',
    storageBucket: 'cpmad-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdUc9ySyZOMpzxRZESl3clxyIeOGZRfjE',
    appId: '1:355747839461:ios:cc1c71b82b9126b959430c',
    messagingSenderId: '355747839461',
    projectId: 'cpmad-assignment',
    storageBucket: 'cpmad-assignment.appspot.com',
    iosBundleId: 'com.example.l1MalcolmCpmadProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdUc9ySyZOMpzxRZESl3clxyIeOGZRfjE',
    appId: '1:355747839461:ios:cc1c71b82b9126b959430c',
    messagingSenderId: '355747839461',
    projectId: 'cpmad-assignment',
    storageBucket: 'cpmad-assignment.appspot.com',
    iosBundleId: 'com.example.l1MalcolmCpmadProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg32UUAsEdUkPN1o44UGGnBhoCNRdk0UI',
    appId: '1:355747839461:web:52e18dce4bbe1c6459430c',
    messagingSenderId: '355747839461',
    projectId: 'cpmad-assignment',
    authDomain: 'cpmad-assignment.firebaseapp.com',
    storageBucket: 'cpmad-assignment.appspot.com',
    measurementId: 'G-0VHWFQ534L',
  );
}
